name: {{fontName}}_icons
description: App cheap custom icons
version: 1.2.0
homepage: https://appcheap.io/

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
flutter:
   fonts:
     - family: {{fontFamily}}
       fonts:
         - asset: fonts/{{fontName}}.ttf
